# This is a basic workflow to help you get started with Actions

name: Page Build

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Update Submodule"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: website
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.LT_SUB }}
          submodules: recursive
          
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: create problems.json
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: |
          pip install BeautifulSoup4
          python createproblemsJson.py 

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
